/** الولايات الجزائرية (58) */
export const WILAYAS: { code: string; ar: string; fr: string }[] = [
  { code: '01', ar: 'أدرار', fr: 'Adrar' },
  { code: '02', ar: 'الشلف', fr: 'Chlef' },
  { code: '03', ar: 'الأغواط', fr: 'Laghouat' },
  { code: '04', ar: 'أم البواقي', fr: 'Oum El Bouaghi' },
  { code: '05', ar: 'باتنة', fr: 'Batna' },
  { code: '06', ar: 'بجاية', fr: 'Béjaïa' },
  { code: '07', ar: 'بسكرة', fr: 'Biskra' },
  { code: '08', ar: 'بشار', fr: 'Béchar' },
  { code: '09', ar: 'البليدة', fr: 'Blida' },
  { code: '10', ar: 'البويرة', fr: 'Bouira' },
  { code: '11', ar: 'تمنراست', fr: 'Tamanrasset' },
  { code: '12', ar: 'تبسة', fr: 'Tébessa' },
  { code: '13', ar: 'تلمسان', fr: 'Tlemcen' },
  { code: '14', ar: 'تيارت', fr: 'Tiaret' },
  { code: '15', ar: 'تيزي وزو', fr: 'Tizi Ouzou' },
  { code: '16', ar: 'الجزائر', fr: 'Alger' },
  { code: '17', ar: 'الجلفة', fr: 'Djelfa' },
  { code: '18', ar: 'جيجل', fr: 'Jijel' },
  { code: '19', ar: 'سطيف', fr: 'Sétif' },
  { code: '20', ar: 'سعيدة', fr: 'Saïda' },
  { code: '21', ar: 'سكيكدة', fr: 'Skikda' },
  { code: '22', ar: 'سيدي بلعباس', fr: 'Sidi Bel Abbès' },
  { code: '23', ar: 'عنابة', fr: 'Annaba' },
  { code: '24', ar: 'قالمة', fr: 'Guelma' },
  { code: '25', ar: 'قسنطينة', fr: 'Constantine' },
  { code: '26', ar: 'المدية', fr: 'Médéa' },
  { code: '27', ar: 'مستغانم', fr: 'Mostaganem' },
  { code: '28', ar: 'المسيلة', fr: "M'Sila" },
  { code: '29', ar: 'معسكر', fr: 'Mascara' },
  { code: '30', ar: 'ورقلة', fr: 'Ouargla' },
  { code: '31', ar: 'وهران', fr: 'Oran' },
  { code: '32', ar: 'البيض', fr: 'El Bayadh' },
  { code: '33', ar: 'إليزي', fr: 'Illizi' },
  { code: '34', ar: 'برج بوعريريج', fr: 'Bordj Bou Arréridj' },
  { code: '35', ar: 'بومرداس', fr: 'Boumerdès' },
  { code: '36', ar: 'الطارف', fr: 'El Tarf' },
  { code: '37', ar: 'تندوف', fr: 'Tindouf' },
  { code: '38', ar: 'تيسمسيلت', fr: 'Tissemsilt' },
  { code: '39', ar: 'الوادي', fr: 'El Oued' },
  { code: '40', ar: 'خنشلة', fr: 'Khenchela' },
  { code: '41', ar: 'سوق أهراس', fr: 'Souk Ahras' },
  { code: '42', ar: 'تيبازة', fr: 'Tipaza' },
  { code: '43', ar: 'ميلة', fr: 'Mila' },
  { code: '44', ar: 'عين الدفلى', fr: 'Aïn Defla' },
  { code: '45', ar: 'النعامة', fr: 'Naâma' },
  { code: '46', ar: 'عين تموشنت', fr: 'Aïn Témouchent' },
  { code: '47', ar: 'غرداية', fr: 'Ghardaïa' },
  { code: '48', ar: 'غليزان', fr: 'Relizane' },
  { code: '49', ar: 'تيميمون', fr: 'Timimoun' },
  { code: '50', ar: 'برج باجي مختار', fr: 'Bordj Badji Mokhtar' },
  { code: '51', ar: 'أولاد جلال', fr: 'Ouled Djellal' },
  { code: '52', ar: 'بني عباس', fr: 'Béni Abbès' },
  { code: '53', ar: 'عين صالح', fr: 'In Salah' },
  { code: '54', ar: 'عين قزام', fr: 'In Guezzam' },
  { code: '55', ar: 'تقرت', fr: 'Touggourt' },
  { code: '56', ar: 'جانت', fr: 'Djanet' },
  { code: '57', ar: 'المغير', fr: "El M'Ghair" },
  { code: '58', ar: 'المنيعة', fr: 'El Meniaa' }
]

export const LEVELS: { code: string; ar: string; order: number }[] = [
  { code: '1AS', ar: 'السنة الأولى ثانوي', order: 1 },
  { code: '2AS', ar: 'السنة الثانية ثانوي', order: 2 },
  { code: '3AS', ar: 'السنة الثالثة ثانوي (بكالوريا)', order: 3 }
]

export const STREAMS: { code: string; ar: string; order: number }[] = [
  { code: 'TC_SCI', ar: 'جذع مشترك علوم وتكنولوجيا', order: 1 },
  { code: 'TC_LIT', ar: 'جذع مشترك آداب', order: 2 },
  { code: 'SCI', ar: 'علوم تجريبية', order: 3 },
  { code: 'MATH', ar: 'رياضيات', order: 4 },
  { code: 'TM', ar: 'تقني رياضي', order: 5 },
  { code: 'GE', ar: 'تسيير واقتصاد', order: 6 },
  { code: 'LIT', ar: 'آداب وفلسفة', order: 7 },
  { code: 'LANG', ar: 'لغات أجنبية', order: 8 }
]

export const SKILLS: { code: string; ar: string; category: string }[] = [
  { code: 'IRAB_SENTENCE', ar: 'إعراب الجمل', category: 'GRAMMAR' },
  { code: 'IRAB_WORD', ar: 'إعراب المفردات', category: 'GRAMMAR' },
  { code: 'IMAGERY', ar: 'الصور البيانية', category: 'RHETORIC' },
  { code: 'RHETORIC_STYLES', ar: 'الأساليب البلاغية', category: 'RHETORIC' },
  { code: 'INTELLECTUAL', ar: 'البناء الفكري', category: 'ANALYSIS' },
  { code: 'LINGUISTIC', ar: 'البناء اللغوي', category: 'ANALYSIS' },
  { code: 'CRITIQUE', ar: 'النقد والتقويم', category: 'ANALYSIS' },
  { code: 'POETRY', ar: 'الشعر', category: 'LITERATURE' },
  { code: 'PROSE', ar: 'النثر', category: 'LITERATURE' },
  { code: 'HAL_TAMYIZ', ar: 'الحال والتمييز', category: 'GRAMMAR' },
  { code: 'PROSODY', ar: 'العروض', category: 'LITERATURE' },
  { code: 'WRITING', ar: 'التعبير الكتابي', category: 'WRITING' }
]
